<METHOD_START> @ Before public void void ( ) java.lang.Exception { org.springframework.data.mongodb.repository.ContactRepository . deleteAll ( ) ; }  <METHOD_END>
<METHOD_START> @ Test public void void ( ) { Person org.springframework.data.mongodb.repository.Person = new Person ( STRING , STRING ) ; Contact org.springframework.data.mongodb.repository.Contact = org.springframework.data.mongodb.repository.ContactRepository . save ( org.springframework.data.mongodb.repository.Person ) ; assertTrue ( org.springframework.data.mongodb.repository.ContactRepository . findOne ( org.springframework.data.mongodb.repository.Contact . getId ( ) . toString ( ) ) . get ( ) instanceof Person ) ; }  <METHOD_END>
<METHOD_START> @ Test public void void ( ) { Person org.springframework.data.mongodb.repository.Person = org.springframework.data.mongodb.repository.ContactRepository . save ( new Person ( STRING , STRING ) ) ; assertThat ( org.springframework.data.mongodb.repository.ContactRepository . findOne ( Example . of ( org.springframework.data.mongodb.repository.Person ) ) , instanceOf ( Person .class ) ) ; }  <METHOD_END>
